### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', clang-sys-1.0.2/src/support.rs:91:48

### ISSUE THREAD

**Issue by JackLiar** [KyleMayes/clang-sys#119]
The new [merged pull request](https://github.com/KyleMayes/clang-sys/pull/118) breaks bindgen building process on my Big Sur machine.

Well, actually there is another problem on my machine:
```shell
✗ xcodebuild -find clang
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

I've no idea how to handle it, maybe it is broken before I upgraded to Big Sur. But all other developments on my machine work like a charm.

So, probably `path.lines()` at line 91 returns an empty string or a single line string, and the `.next()` returns None, then bindgen failed.

**Comment by KyleMayes** [comment]
I have released a fix for this as `v1.0.3`.

This panic is triggered by `llvm-config` or `xcodebuild` not printing anything to `stdout`, presumably in your case `xcodebuild` is only printing to `stderr` since Xcode is not installed. `v1.0.3` will ignore the result of executing the command if nothing is printed to `stdout`.
