### ISSUE TITLE
Static link failure

### ISSUE THREAD

**Issue by Yamakaky** [KyleMayes/clang-sys#14]
https://travis-ci.org/crabtw/rust-bindgen/jobs/129524942

**Comment by KyleMayes** [comment]
Working on a solution.

**Comment by Yamakaky** [comment]
Tip: in bindgen, replace the clang-sys version by a path to a local checkout of clang-sys. You can then easily test changes in clang-sys. It would be better to have a dummy test bin, though.

**Comment by Yamakaky** [comment]
In fact no, you can simply run `cargo test --features static`.

**Comment by KyleMayes** [comment]
Yeah, that's what I thought.
I'm closer to a solution now, static linking is working with 3.5, 3.6, and 3.7 on Linux.

**Comment by KyleMayes** [comment]
I'm stumped, it seems the 3.8 releases neglected to include `libclang.a`. We may need to disallow static linking in this case. I'm emailing the clang mailing lists to see what this is about.

**Comment by Yamakaky** [comment]
ahah ^^

**Comment by KyleMayes** [comment]
OK, static linking [works](https://travis-ci.org/KyleMayes/clang-sys/builds/129857691) on Linux and OS X for clang < 3.8.

I added a `LLVM_CONFIG_PATH` environment variable for setting the path to an `llvm-config` executable. This is necessary because `llvm-config --libs` returns different lists of libraries depending on the version of LLVM `llvm-config` was compiled for. This means you need to set this to test static linking so you don't get linking errors ([Linux](https://github.com/KyleMayes/clang-sys/blob/eb34ecde409d25f3dfd0ecc1c822cb33e5e118c2/.travis.yml#L6), [OS X](https://github.com/KyleMayes/clang-sys/blob/eb34ecde409d25f3dfd0ecc1c822cb33e5e118c2/.travis.yml#L98)).

**Comment by Yamakaky** [comment]
cool!
