### ISSUE TITLE
static build fail

### ISSUE THREAD

**Issue by Yamakaky** [KyleMayes/clang-sys#15]
https://travis-ci.org/crabtw/rust-bindgen/jobs/132283528

**Comment by KyleMayes** [comment]
Judging by the error, `libclangRewrite.a` is not part of Clang 3.4. The list of required Clang static libraries is hardcoded because there is no Clang equivalent of `llvm-config --libs`. I've already cut the hardcoded list down to the minimum required for Clang 3.5+, so Clang 3.4 is not supported for static linking.

**Comment by Yamakaky** [comment]
Good to know ^^

**Comment by Yamakaky** [comment]
So 3.4 is not supported?

**Comment by KyleMayes** [comment]
I guess I can have 3.4 be unofficially supported. I'm working on using glob to find the Clang libraries, that should fix the static linking issue. Other than that, 3.4 should work fine.
