### ISSUE TITLE
lib.rs seems hand written, why bindgen was not used in the first place?

### ISSUE THREAD

**Issue by ssh352** [KyleMayes/clang-sys#160]
Thanks

**Comment by KyleMayes** [comment]
This crate doesn't pre-date `bindgen`, but `bindgen` was in its very early days when this crate was created. Also, the original purpose of this crate was to support the creation of my own C bindings generator (which never materialized).

Using `bindgen` would be a pretty big change for little benefit since adding support for new versions of `libclang` only needs to happen every 6 months and usually doesn't take much effort.
