### ISSUE TITLE
Provide an API to get the `clang` matching the loaded `libclang.so`

### ISSUE THREAD

**Issue by jschwe** [KyleMayes/clang-sys#171]
Currently, `bindgen` uses `clang_sys::support::Clang::find` to determine a clang compiler which can be used to determine which [system header files to include](https://github.com/rust-lang/rust-bindgen/blob/main/bindgen/lib.rs). In practice, this seems to return the **default** clang version, e.g. `clang-14` on Ubuntu 22.04.
`bindgen` however also uses `libclang-sys` to parse C-code, which would use the **most recent** version of libclang. 
On Ubuntu 22.04 one can for example install `clang-15`. In this case there is a mismatch in bindgen between the libclang version used to do the parsing, and the included system headers, which can lead to hard errors such as missing builtins.

To resolve this, perhaps `clang-sys` could provide an API which returns a path to the `clang` executable matching the used libclang version (both with and without the `runtime` feature). 

Related bindgen issue: https://github.com/rust-lang/rust-bindgen/issues/2682

**Comment by KyleMayes** [comment]
Instead of a separate API, I'm looking into improving `clang_sys::support::Clang::find` to take into account runtime-loaded `libclang` instances (if any).

I've added a commit (unreleased as of yet) that makes it so that directories adjacent to the runtime-loaded `libclang` instance are checked for `clang` executables. In my testing when setting `LIBCLANG_PATH` to point to a custom build of LLVM + Clang, the found `clang` executable is from the custom build rather than the system-provided one.

I'm not sure what to do about dynamically-linked `libclang` instances since the path could differ each run of the executable in question. Runtime linking is the default for `rust-bindgen` so my change should be good enough for most users.

**Comment by jschwe** [comment]
Thanks! I believe that at least for my use-cases this should be sufficient.

**Comment by bonzini** [comment]
This is not enough because you could have multiple versions on the same path. For example on Debian you could have `/usr/bin/clang-14` and `/usr/bin/clang-17`, and `/usr/bin/clang` can point to any of the two.

If libclang is v17, but `/usr/bin/clang` is v14, the detected paths will be incorrect.

**Comment by jschwe** [comment]
Reopening, since 1.8.2 (and 1.9.0) got yanked, and thus never released.
