### ISSUE TITLE
linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by alickbass** [KyleMayes/clang-sys#81]
Hi! I am trying to use statically link clang-sys on Mac in my pet hello world project. So I downloaded and compiled libclang version 6_0_0 and it has all the necessary files (libclang.a llvm-config etc). Here's my Cargo.toml

```
[package]
name = "hello_libclang"
version = "0.1.0"
authors = ["Oleksii Dykan <alickbass@gmail.com>"]

[dependencies]

[dependencies.clang-sys]
version = "0.24.0"
features = ["static", "clang_6_0"]
```

and here's my `main.rs`:

```
extern crate clang_sys;

fn main() {
    println!("Hello, world!");
}
```
I try to compile it with the following command:

```
LLVM_CONFIG_PATH=~/Desktop/clang-test/build/bin/llvm-config LIBCLANG_STATIC_PATH=~/Desktop/clang-test/build/lib LIBCLANG_PATH=~/Desktop/clang-test/build/lib cargo build
```
however, on the compilation time I get the following error:

```
error: linking with `cc` failed: exit code: 1
```

Do you know what could be the reason for that? Thanks in advance!

**Comment by KyleMayes** [comment]
Sorry about the (very) late response.

Judging by the error this looks like it is probably a macOS-specific issue.
If so, I won't be of much help because I have never worked with macOS in any significant capacity.

However, I will try building and linking to `clang` statically on Linux to verify that it still works.

**Comment by alickbass** [comment]
@KyleMayes you're awesome! I really appreciate it!
