### ISSUE TITLE
clang-sys isn't using semver correctly

### ISSUE THREAD

**Issue by jsgf** [KyleMayes/clang-sys#96]
I mentioned this in passing in #95 but its worth calling out explicitly.

It looks like subsequent versions of clang-sys have just been adding new APIs, but not breaking old ones; for example 0.23.0's API seems to be a strict subset of 0.28.0's API.

However, incrementing the version from 0.X to 0.Y is not compatible from a semver perspective which will force something that depends on `clang-sys ^0.23` to resolve a different version from one depending on `^0.28`, whereas in practice they could both use 0.28's API.

Semver's rules for 0.x is different from >= 1.0 - 1.1 and 1.2 would be semver compatible, as would 0.1.1 and 0.1.2.

clang-sys should move to a model where new backwards-compatible releases are 0.28.x, or move to 1.x.

**Comment by jsgf** [comment]
@dtolnay suggested introducing a crate which is just responsible for linkage with libclang, separate from clang-sys which is responsible for presenting an API. So, for example `clang-sys-linkage` could have `link = "clang"` and be fixed at 1.0 for as long as libclang has a backwards-compatible API. Numerous `clang-sys` crates, with potentially incompatible APIs, could depend on `clang-sys-linkage 1.0`, so that cargo would be happy to allow multiple versions of clang-sys in the one dependency graph while retaining the invariant of only one `link = "clang"` crate.

This could be introduced retroactively by releasing patch versions of each supported version of clang-sys.

**Comment by KyleMayes** [comment]
To me, there is more to backwards compatibility than API compatibility. For example, if a new version of a library has the exact same API but the implementation uses features from a new version of Rust (such as I did recently as reported in #94), that can break peoples' builds if those changes are released with a semver version that indicates compatibility with the previous version.

There have been several instances where my attempts to improve the `libclang` finding and linking code in ways I thought was backwards compatible has caused the library to pick different versions of `libclang` or stop finding a version of `libclang` it was finding before.

As such, I have started avoiding releasing backwards compatible versions whenever I make non-trivial changes to the `libclang` finding and linking code so as to not break peoples' builds.

However, the finding and linking code has been very stable recently with no changes to the core logic in months and I do like the idea of decoupling the version of the finding and linking code from the version of the rest of the library.

**Comment by jsgf** [comment]
Well the combination of `links = "clang"` and using non-semver-compat versions means that lots of reasonable combinations of crates fail to resolve if they happen to get into the wrong state.

I think part of the problem here is that clang-sys is a bit unusual as -sys crates go, in that it has its own API and lots of other crates consume it directly. The more common pattern is that a -sys crate exposes the C API in an extremely raw way, and the corresponding non-sys crate has the actual API that everyone depends on. So in essence the "-linkage" crate proposed above becomes the "real" -sys crate, clang-sys is the "low-level" API that is expected to be used, and "clang" is the high-level API. (zstd/zstd-safe/zstd-sys is an example of a similar pattern.)

**Comment by MOZGIII** [comment]
Sevmer is not strictly misused here, the use case is perfectly correct from the semver's perspective.

The ecosystem we ended up having around this library is a huge pain to work with. The `-linkage` crate solution would fix it, however I'm afraid it'll take a lot of time to adopt though - cause it takes a ripple effect to get people up to date with latest `clang-sys` once we roll out the `-linkage` crate update.

**Comment by jsgf** [comment]
@MOZGIII That's not necessarily true - one could publish patch revision to all the outstanding clang-sys versions in use to add the -linkage dependency (eg 0.28.x, 0.27.y, 0.29.z).

(Ran into this again and came back to see if anything had changed.)

**Comment by KyleMayes** [comment]
@jsgf @MOZGIII 

I've (finally) made some progress on this front, I have a [branch](https://github.com/KyleMayes/clang-sys/tree/linkage) which splits the linking build script and `links` manifest key into a separate crate called `clang-sys-linkage` as suggested.

However, it does not work as currently implemented. Now that `libclang` is linked to by the `clang-sys-linkage` crate and not the `clang-sys` crate, I get undefined reference errors to the `libclang` functions in the `clang-sys` crate.

Is the idea that the `clang-sys-linkage` crate should exist purely for the `links` manifest key, with `clang-sys` still handling finding and linking to `libclang` as it does today? Or should the `clang-sys-linkage` crate handle finding `libclang` and then providing the found library information to any dependent `clang-sys` crate versions through build script metadata so that they can then link to the found `libclang` library themselves?

The [section of the Cargo book about the `links` manifest key](https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key) says:

"When using the links key, the package must have a build script, and the build script should use the rustc-link-lib instruction to link the library.

Primarily, Cargo requires that there is at most one package per links value. In other words, it is forbidden to have two packages link to the same native library. This helps prevent duplicate symbols between crates. Note, however, that there are conventions in place to alleviate this."

I'm not sure if these are hard requirements that could cause issues if bypassed, or if it's OK for there to be multiple `clang-sys` crate versions linking to `libclang` as long as they all use the same finding logic from the same version of `clang-sys-linkage` so that they are all linking to the same instance of `libclang`.

Alternatively I could just release `v1.0.0` and call it a day.

Sorry for not getting to this sooner!

**Comment by jsgf** [comment]
@KyleMayes Thanks for working on this. I'll take a look at what you've got to see if I can help out when I get the chance (should be in the next few days).

**Comment by KyleMayes** [comment]
Having thought about this some more, I think I just misunderstood what I was trying to accomplish.

The course of action I think I will investigate now is creating a branch where I just rename the `clang-sys` crate to `clang-sys-linkage` and publish it as `v1.0.0`. Then I will create patch releases for the last couple minor versions of `clang-sys` (`v0.29.4`, `v0.28.2`, etc.) that rip out the guts of `clang-sys`, add the `clang-sys-linkage` dependency, and re-export everything from `clang-sys-linkage` from `clang-sys`.

I'm now thinking of the `clang-sys-linkage` crate as a backwards-compatible bump to `v1.0.0` that will be obsoleted once the `clang-sys` crate itself is bumped to `v1.0.0`, which I plan on doing once this whole debacle is resolved.

**Comment by jsgf** [comment]
Yeah that sounds like a workable strategy.

**Comment by KyleMayes** [comment]
The following patch versions have been released for previous minor versions with the `clang-sys-linkage` workaround:

* `v0.29.4`
* `v0.28.2`
* `v0.27.1`

That goes back almost two years of releases since `clang-sys` hasn't seen many changes recently. Hopefully that is enough to resolve the problem until `bindgen` updates `clang-sys` to `v1.0.0` and then enough crates in the ecosystem upgrade to that version of `bindgen`.

**Comment by KyleMayes** [comment]
Welp this was a disaster.
Were just going to have to wait until the ecosystem moves to `v1.0.0` and above.

**Comment by jsgf** [comment]
Oh what happened with the 0.2x.y releases?
